spring.application.name=eduplan-backend

spring.datasource.url=jdbc:mysql://localhost:3306/eduplan
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
